class_name GAME_LIMITS

class ENERGY:
    class MINING:
        class LOW:
            const CAUTION = 0.125 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM
            const DANGER = 0.0625 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM
            const END_OF_GAME = GAME_PARAMETERS.EXTREMA.ENERGY.MINIMUM

        class HIGH:
            const CAUTION = 1.1 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM
            const DANGER = 1.25 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM
            const END_OF_GAME = 1.5 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM

    class TAKE_OFF:
        class LOW:
            const END_OF_GAME = 0.0625 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM

        class HIGH:
            const END_OF_GAME = 1.5 * GAME_PARAMETERS.EXTREMA.ENERGY.MAXIMUM

class O2:
    class LOW:
        const CAUTION = 0.69 * GAME_PARAMETERS.EXTREMA.ATMOSPHERE.O2.MAXIMUM
        const DANGER = 0.57 * GAME_PARAMETERS.EXTREMA.ATMOSPHERE.O2.MAXIMUM
        const END_OF_GAME = GAME_PARAMETERS.EXTREMA.ATMOSPHERE.O2.MINIMUM

class CO2:
    class HIGH:
        const CAUTION = 0.375 * GAME_PARAMETERS.EXTREMA.ATMOSPHERE.CO2.MAXIMUM
        const DANGER = 0.75 * GAME_PARAMETERS.EXTREMA.ATMOSPHERE.CO2.MAXIMUM
        const END_OF_GAME = GAME_PARAMETERS.EXTREMA.ATMOSPHERE.CO2.MAXIMUM

class WEAR:
    class HIGH:
        const CAUTION = 0.5 * GAME_PARAMETERS.EXTREMA.WEAR.MAXIMUM
        const DANGER = 0.75 * GAME_PARAMETERS.EXTREMA.WEAR.MAXIMUM
        const END_OF_GAME = 1.1 * GAME_PARAMETERS.EXTREMA.WEAR.MAXIMUM

class WEIGHT:
    class HIGH:
        const CAUTION = 0.85 * GAME_PARAMETERS.EXTREMA.ROCKET.WEIGHT.GROSS.MAXIMUM
        const DANGER = 1.1 * GAME_PARAMETERS.EXTREMA.ROCKET.WEIGHT.GROSS.MAXIMUM
        const END_OF_GAME = 2 * GAME_PARAMETERS.EXTREMA.ROCKET.WEIGHT.GROSS.MAXIMUM


    # const CAUTION
    # const DANGER
    # const END_OF_GAME